<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vjeventdb3"
 *
 * Auto generated by Extension Builder 2014-08-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Event Database',
	'description' => 'A rich-featured event database based on ext and fluid.',
	'category' => 'plugin',
	'author' => 'Vincent Tietz',
	'author_email' => 'vincent.tietz@vj-media.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.6',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'sr_freecap' => '2.0.8'
		),
	),
);
