<?php
namespace VJmedia\Vjeventdb3\Domain\Model;

/***************************************************************
 *
 *  Copyright notice
 *
 *  (c) 2014 Vincent Tietz <vincent.tietz@vj-media.de>, vjmedia
 *
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

/**
 * Date
 */
class Date extends \TYPO3\CMS\Extbase\DomainObject\AbstractEntity {

	/**
	 * Once.
	 */
	const FREQUENCY_ONCE = 0;
	
	/**
	 * Daily.
	 */
	const FREQUENCY_DAILY = 1;
	
	/**
	 * Weely.
	 */
	const FREQUENCY_WEEKLY = 2;
	
	/**
	 * Monthly.
	 */
	const FREQUENCY_MONTHLY = 3;
	
	/**
	 * Yearly.
	 */
	const FREQUENCY_YEARLY = 4;
	
	/**
	 * startDate
	 *
	 * @var \DateTime
	 * @validate NotEmpty
	 */
	protected $startDate = NULL;

	/**
	 * startTime
	 *
	 * @var integer
	 */
	protected $startTime = 0;

	/**
	 * endDate
	 *
	 * @var \DateTime
	 */
	protected $endDate = NULL;

	/**
	 * endTime
	 *
	 * @var integer
	 */
	protected $endTime = 0;

	/**
	 * frequency
	 *
	 * @var integer
	 */
	protected $frequency = 0;

	/**
	 * title
	 *
	 * @var string
	 */
	protected $title = '';

	/**
	 * text
	 *
	 * @var string
	 */
	protected $text = '';

	/**
	 * @var integer
	 */
	protected $sorting;
	
	/**
	 * events
	 *
	 * @var \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\VJmedia\Vjeventdb3\Domain\Model\Event>
	 */
	protected $events = NULL;
	
	
	protected $duration = '';
	
	/**
	 * Represents an exceptional date. Is added by DateService::addExceptionalDates().
	 * @var VJmedia\Vjeventdb3\Domain\Model\ExceptionalDate
	 */
	protected $exceptionalDate = NULL;
	
	/**
	 * Represents the timestamp of start date and start time. Is generated by DateService.
	 * @var int
	 */
	protected $startTimestamp = 0;
	
	/**
	 * Returns the startDate
	 *
	 * @return \DateTime $startDate
	 */
	public function getStartDate() {
		return $this->startDate;
	}

	/**
	 * Sets the startDate
	 *
	 * @param \DateTime $startDate
	 * @return void
	 */
	public function setStartDate(\DateTime $startDate) {
		$this->startDate = $startDate;
	}

	/**
	 * Returns the startTime
	 *
	 * @return integer $startTime
	 */
	public function getStartTime() {
		return $this->startTime;
	}

	/**
	 * Sets the startTime
	 *
	 * @param integer $startTime
	 * @return void
	 */
	public function setStartTime($startTime) {
		$this->startTime = $startTime;
	}

	/**
	 * Returns the endDate
	 *
	 * @return \DateTime $endDate
	 */
	public function getEndDate() {
		return $this->endDate;
	}

	/**
	 * Sets the endDate
	 *
	 * @param \DateTime $endDate
	 * @return void
	 */
	public function setEndDate(\DateTime $endDate) {
		$this->endDate = $endDate;
	}

	/**
	 * Returns the endTime
	 *
	 * @return integer $endTime
	 */
	public function getEndTime() {
		return $this->endTime;
	}

	/**
	 * Sets the endTime
	 *
	 * @param integer $endTime
	 * @return void
	 */
	public function setEndTime($endTime) {
		$this->endTime = $endTime;
	}

	/**
	 * Returns the frequency
	 *
	 * @return integer $frequency
	 */
	public function getFrequency() {
		return $this->frequency;
	}

	/**
	 * Sets the frequency
	 *
	 * @param integer $frequency
	 * @return void
	 */
	public function setFrequency($frequency) {
		$this->frequency = $frequency;
	}

	/**
	 * Returns the title
	 *
	 * @return string $title
	 */
	public function getTitle() {
		return $this->title;
	}

	/**
	 * Sets the title
	 *
	 * @param string $title
	 * @return void
	 */
	public function setTitle($title) {
		$this->title = $title;
	}

	/**
	 * Returns the text
	 *
	 * @return string $text
	 */
	public function getText() {
		return $this->text;
	}

	/**
	 * Sets the text
	 *
	 * @param string $text
	 * @return void
	 */
	public function setText($text) {
		$this->text = $text;
	}

	/**
	 * Sets the sorting.
	 * 
	 * @param integer $sorting
	 */
	public function setSorting($sorting) {
		$this->sorting = $sorting;
	}
	
	/**
	 * Returns the sorting.
	 * 
	 * @return integer $sorting
	 */
	public function getSorting() {
		return $this->sorting;
	}
	
	
	/**
	 * Sets the sorting.
	 *
	 * @param integer $sorting
	 */
	public function setEvent($event) {
		$this->event = $event;
	}
	
	/**
	 * Returns the event.
	 *
	 * @return \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\VJmedia\Vjeventdb3\Domain\Model\Event> $event
	 */
	public function getEvent() {
		return $this->event;
	}	

	public function setDuration($duration) {
		$this->duration = $duration;
	}
	
	public function getDuration() {
		return $this->duration;
	}
	
	public function setExceptionalDate($exceptionalDate) {
		$this->exceptionalDate = $exceptionalDate;
	}

	public function getExceptionalDate() {
		return $this->exceptionalDate;
	}
	
	/**
	 * @return bool True if hidden
	 */
	public function isHidden() {
		return $this->hidden;
	}
	
	/**
	 * @param int $startTimestamp The startTimestamp;
	 */
	public function setStartTimestamp($startTimestamp) {
		$this->startTimestamp = $startTimestamp;
	}

	/**
	 * The startTimestamp;
	 * 
	 * @return int startTimestamp
	 */
	public function getStartTimestamp() {
		return $this->startTimestamp;
	}
	
	
	
}